"""
utils/report_generator.py
Generates a professional PDF report from the insurance comparison data.
"""

import io
import re
import datetime
from typing import Dict, Any, List
from fpdf import FPDF


class InsuranceReportPDF(FPDF):
    """Custom PDF class with header/footer for InsureIQ reports."""

    DARK_BG = (15, 23, 42)
    HEADER_BG = (99, 102, 241)
    ROW_EVEN = (30, 41, 59)
    ROW_ODD = (20, 30, 48)
    TEXT_PRIMARY = (226, 232, 240)
    TEXT_SECONDARY = (148, 163, 184)
    ACCENT = (165, 180, 252)
    GREEN = (52, 211, 153)
    RED = (239, 68, 68)
    YELLOW = (245, 158, 11)
    WHITE = (255, 255, 255)

    def __init__(self):
        super().__init__(orientation="L", format="A4")
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Background
        self.set_fill_color(*self.DARK_BG)
        self.rect(0, 0, self.w, self.h, "F")
        # Header bar
        self.set_fill_color(*self.HEADER_BG)
        self.rect(0, 0, self.w, 16, "F")
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*self.WHITE)
        self.set_y(4)
        self.cell(0, 8, "InsureIQ  -  Insurance Policy Comparison Report", align="C")
        # Date
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*self.TEXT_SECONDARY)
        self.set_xy(self.w - 55, 4)
        self.cell(50, 8, datetime.datetime.now().strftime("%d %b %Y, %I:%M %p"), align="R")
        self.ln(16)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*self.TEXT_SECONDARY)
        self.cell(0, 8, f"Page {self.page_no()}/{{nb}}  |  Generated by InsureIQ AI", align="C")

    # ── Utility drawing helpers ──────────────────────────────────────────

    def _section_title(self, icon: str, title: str):
        """Draw a styled section title."""
        self.ln(4)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*self.ACCENT)
        self.cell(0, 9, f"  {icon}  {title}", ln=True)
        # Underline
        self.set_draw_color(*self.HEADER_BG)
        self.set_line_width(0.6)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def _draw_table(self, headers: List[str], rows: List[List[str]],
                    col_widths: List[float] = None):
        """
        Draw a styled table with alternating row colors.
        """
        available_width = self.w - self.l_margin - self.r_margin
        if col_widths is None:
            col_widths = [available_width / len(headers)] * len(headers)
        else:
            # Scale col_widths to fit available width
            total = sum(col_widths)
            col_widths = [w / total * available_width for w in col_widths]

        row_height = 8

        # Header row
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(*self.HEADER_BG)
        self.set_text_color(*self.WHITE)
        for i, header in enumerate(headers):
            self.cell(col_widths[i], row_height + 2, f" {header}", border=0,
                      fill=True, align="C")
        self.ln(row_height + 2)

        # Data rows
        self.set_font("Helvetica", "", 7.5)
        for row_idx, row in enumerate(rows):
            # Check if we need a new page
            if self.get_y() + row_height + 2 > self.h - 20:
                self.add_page()

            bg = self.ROW_EVEN if row_idx % 2 == 0 else self.ROW_ODD
            self.set_fill_color(*bg)

            # Calculate the max number of lines needed for this row
            max_lines = 1
            cell_texts = []
            for i, cell in enumerate(row):
                text = str(cell).strip()
                cell_texts.append(text)
                # Estimate lines needed
                char_width = self.get_string_width("A")
                if char_width > 0:
                    chars_per_line = max(1, int(col_widths[i] / char_width))
                    lines_needed = max(1, (len(text) + chars_per_line - 1) // chars_per_line)
                    max_lines = max(max_lines, lines_needed)

            actual_row_h = max(row_height, max_lines * 4.5 + 3)

            # First column styling (feature name)
            self.set_text_color(*self.ACCENT)
            self.set_font("Helvetica", "B", 7.5)
            x_start = self.get_x()
            y_start = self.get_y()

            for i, text in enumerate(cell_texts):
                if i == 0:
                    self.set_text_color(*self.ACCENT)
                    self.set_font("Helvetica", "B", 7.5)
                else:
                    self.set_text_color(*self.TEXT_PRIMARY)
                    self.set_font("Helvetica", "", 7.5)

                self.set_xy(x_start + sum(col_widths[:i]), y_start)
                # Draw cell background
                self.set_fill_color(*bg)
                self.rect(x_start + sum(col_widths[:i]), y_start,
                          col_widths[i], actual_row_h, "F")
                # Draw cell text
                self.set_xy(x_start + sum(col_widths[:i]) + 1, y_start + 1)
                self.multi_cell(col_widths[i] - 2, 4.5, text, align="L")

            self.set_y(y_start + actual_row_h)

    def _paragraph(self, text: str):
        """Draw a paragraph of body text."""
        self.set_font("Helvetica", "", 8.5)
        self.set_text_color(*self.TEXT_PRIMARY)
        self.multi_cell(0, 5, text)
        self.ln(2)


def _parse_markdown_table(md_table: str) -> tuple:
    """
    Parse a markdown table string into headers and rows.
    Returns (headers: List[str], rows: List[List[str]])
    """
    lines = [l.strip() for l in md_table.strip().split("\n") if l.strip()]
    if not lines:
        return [], []

    # Filter out separator lines (e.g., |---|---|)
    data_lines = []
    for line in lines:
        cleaned = line.strip("|").strip()
        if cleaned and not all(c in "-| " for c in cleaned):
            data_lines.append(line)

    if not data_lines:
        return [], []

    headers = [c.strip() for c in data_lines[0].strip("|").split("|")]
    rows = []
    for line in data_lines[1:]:
        cells = [c.strip() for c in line.strip("|").split("|")]
        rows.append(cells)

    return headers, rows


def generate_comparison_pdf(comparison_result: Dict[str, Any],
                            hidden_clauses: Dict[str, List[Dict]] = None,
                            recommendation: Dict[str, Any] = None,
                            policy_names: List[str] = None) -> bytes:
    """
    Generate a comprehensive PDF report from comparison data.

    Args:
        comparison_result: Output from GeminiHelper.compare_policies()
        hidden_clauses: Output from GeminiHelper.detect_hidden_clauses()
        recommendation: Output from GeminiHelper.get_recommendation()
        policy_names: List of policy names

    Returns:
        PDF file content as bytes.
    """
    pdf = InsuranceReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # ── Title Section ────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*InsuranceReportPDF.WHITE)
    pdf.ln(2)
    pdf.cell(0, 12, "Insurance Policy Comparison Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*InsuranceReportPDF.TEXT_SECONDARY)
    if policy_names:
        pdf.cell(0, 6, f"Policies Analyzed: {', '.join(policy_names)}", ln=True, align="C")
    pdf.cell(0, 6,
             f"Generated on {datetime.datetime.now().strftime('%d %B %Y at %I:%M %p')}",
             ln=True, align="C")
    pdf.ln(6)

    # ── 1. Comparison Table ──────────────────────────────────────────────
    if comparison_result:
        pdf._section_title("1.", "Policy Comparison Table")

        table_md = comparison_result.get("table", "")
        if table_md:
            headers, rows = _parse_markdown_table(table_md)
            if headers and rows:
                # First column wider for feature names
                col_widths = [2.0] + [1.5] * (len(headers) - 1)
                pdf._draw_table(headers, rows, col_widths)
            else:
                pdf._paragraph("Comparison data not available in tabular format.")
        else:
            pdf._paragraph("Comparison table not available.")

        # ── 2. Key Metrics Summary ───────────────────────────────────────
        metrics = comparison_result.get("metrics", {})
        if metrics:
            pdf.ln(4)
            pdf._section_title("2.", "Key Metrics Summary")

            metric_headers = ["Metric"]
            for pname in metrics.keys():
                metric_headers.append(pname)

            # Gather all unique metric keys
            all_keys = []
            for pdata in metrics.values():
                for k in pdata.keys():
                    if k not in all_keys:
                        all_keys.append(k)

            metric_rows = []
            for key in all_keys:
                row = [key]
                for pname in metrics.keys():
                    row.append(str(metrics[pname].get(key, "N/A")))
                metric_rows.append(row)

            col_widths = [2.0] + [1.5] * (len(metric_headers) - 1)
            pdf._draw_table(metric_headers, metric_rows, col_widths)

        # ── 3. Winner ────────────────────────────────────────────────────
        winner = comparison_result.get("winner", "")
        winner_reason = comparison_result.get("winner_reason", "")
        if winner:
            pdf.ln(4)
            pdf._section_title("3.", "Overall Best Policy")
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*InsuranceReportPDF.GREEN)
            pdf.cell(0, 7, f"  Winner:  {winner}", ln=True)
            if winner_reason:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*InsuranceReportPDF.TEXT_PRIMARY)
                pdf.multi_cell(0, 5, f"  Reason: {winner_reason}")
            pdf.ln(2)

        # ── 4. Detailed AI Analysis ──────────────────────────────────────
        summary = comparison_result.get("summary", "")
        if summary:
            pdf.ln(2)
            section_num = 4 if winner else 3
            pdf._section_title(f"{section_num}.", "Detailed AI Analysis")
            pdf._paragraph(summary)

    # ── 5. Hidden Clauses ────────────────────────────────────────────────
    if hidden_clauses:
        pdf.add_page()
        pdf._section_title("5.", "Hidden Clause & Risk Analysis")

        for policy_name, items in hidden_clauses.items():
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*InsuranceReportPDF.ACCENT)
            pdf.cell(0, 7, f"  Policy: {policy_name}", ln=True)
            pdf.ln(1)

            if not items:
                pdf.set_font("Helvetica", "", 8.5)
                pdf.set_text_color(*InsuranceReportPDF.GREEN)
                pdf.cell(0, 6, "    No major hidden clauses detected.", ln=True)
            else:
                clause_headers = ["#", "Clause", "Severity", "Explanation"]
                clause_rows = []
                for i, item in enumerate(items, 1):
                    clause_rows.append([
                        str(i),
                        item.get("clause", "N/A"),
                        item.get("severity", "N/A").upper(),
                        item.get("explanation", "N/A")
                    ])
                col_widths = [0.3, 1.5, 0.7, 4.0]
                pdf._draw_table(clause_headers, clause_rows, col_widths)

            pdf.ln(4)

    # ── 6. Recommendation ────────────────────────────────────────────────
    if recommendation:
        if not hidden_clauses:
            pdf.add_page()
        pdf._section_title("6.", "Personalized Recommendation")

        rec_policy = recommendation.get("recommended_policy", "N/A")
        rec_reason = recommendation.get("reason", "")
        fit_score = recommendation.get("fit_score", "")

        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*InsuranceReportPDF.GREEN)
        pdf.cell(0, 7, f"  Recommended:  {rec_policy}", ln=True)
        if fit_score:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*InsuranceReportPDF.YELLOW)
            pdf.cell(0, 6, f"  Fit Score: {fit_score}/10", ln=True)
        pdf.ln(2)

        if rec_reason:
            pdf._paragraph(f"Reason: {rec_reason}")

        pros = recommendation.get("pros", [])
        if pros:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*InsuranceReportPDF.GREEN)
            pdf.cell(0, 6, "  Advantages:", ln=True)
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*InsuranceReportPDF.TEXT_PRIMARY)
            for pro in pros:
                pdf.cell(0, 5, f"    +  {pro}", ln=True)
            pdf.ln(2)

        cons = recommendation.get("cons", [])
        if cons:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*InsuranceReportPDF.RED)
            pdf.cell(0, 6, "  Limitations:", ln=True)
            pdf.set_font("Helvetica", "", 8.5)
            pdf.set_text_color(*InsuranceReportPDF.TEXT_PRIMARY)
            for con in cons:
                pdf.cell(0, 5, f"    -  {con}", ln=True)
            pdf.ln(2)

        alternatives = recommendation.get("alternatives", "")
        if alternatives:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*InsuranceReportPDF.ACCENT)
            pdf.cell(0, 6, "  Alternative Options:", ln=True)
            pdf._paragraph(f"  {alternatives}")

    # ── Disclaimer Footer ────────────────────────────────────────────────
    pdf.ln(6)
    pdf.set_draw_color(*InsuranceReportPDF.HEADER_BG)
    pdf.set_line_width(0.3)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(*InsuranceReportPDF.TEXT_SECONDARY)
    pdf.multi_cell(0, 4,
                   "Disclaimer: This report is generated by AI analysis and is intended for "
                   "informational purposes only. It does not constitute financial or legal advice. "
                   "Always read the complete policy document and consult a certified insurance "
                   "advisor before making any purchase decisions.")

    # Output
    return pdf.output()
